# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AbJna14nvtVJ7rtqHj62QwaSYzG0XzW
"""

import pandas as pd
Oqituvchilar =pd.DataFrame({
"Ism Familya":["Jo'rayeva G.F","Xalilov D.A",'Turdimatov M.M','Xontorayev S.I','Mirkomilov M.D','DjalilovM.L','Qadamova Z.E'],
'fan turi':['majburiy','majburiy','majburiy','majburiy','majburiy','majburiy','majburiy'],
'Dars soati':['180','180','180','180','180','180','180'],
 'mustaqil talim':['108','108','108','108','108','108','108'],
})
print(Oqituvchilar)